# Generated by Django 4.0.4 on 2022-05-04 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0004_comentcrm'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='order_name',
            field=models.CharField(max_length=200, unique=True, verbose_name='Имя'),
        ),
    ]
