# Generated by Django 4.0.4 on 2022-04-20 13:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('price', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='PriceTabable',
            new_name='PriceTable',
        ),
        migrations.RenameField(
            model_name='pricetable',
            old_name='new_price',
            new_name='pt_new_price',
        ),
        migrations.RenameField(
            model_name='pricetable',
            old_name='old_price',
            new_name='pt_old_price',
        ),
    ]
